In [1]:
import pandas as pd

In [10]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("juhibhojani/house-price")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Lenovo\.cache\kagglehub\datasets\juhibhojani\house-price\versions\1

In [11]:
import os
os.getcwd()

'C:\\Users\\Lenovo'

In [14]:
s = pd.read_csv('C:\\Users\\Lenovo\\house_prices.csv')

In [46]:
s.describe()
s.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,Bathroom,Balcony,Ownership
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,1,2,Unknown
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,2,0,Freehold
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,2,0,Freehold
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,1,1,Unknown
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,2,0,Co-operative Society

In [20]:
s.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [23]:
s.drop(columns=['Dimensions','Plot Area'], inplace = True)

In [31]:
s.drop(columns = ['facing'], inplace = True)

In [56]:
s.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,Bathroom,Balcony,Ownership
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,1.0,2,Unknown
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,2.0,0,Freehold
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,2.0,0,Freehold
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,1.0,1,Unknown
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,2.0,0,Co-operative Society

In [52]:
s.fillna({"Furnishing":s["Furnishing"].mode()[0]}, inplace = True)
s.fillna({"Balcony": 0}, inplace=True)
s["Bathroom"] = pd.to_numeric(s["Bathroom"], errors="coerce")
s["Bathroom"] = s["Bathroom"].fillna(s["Bathroom"].median())


s.fillna({"Status":"Unknown"}, inplace = True)
s.fillna({"Ownership":"Unknown"}, inplace = True)
s.fillna({"Transaction":s["Transaction"].mode()[0]}, inplace = True)
s.fillna({"Price (in rupees)":s["Price (in rupees)"].mean()}, inplace = True)
s.fillna({"Floor":"Unknown"}, inplace = True)

In [55]:
s.isnull().sum()

Index                    0
Title                    0
Description           3023
Amount(in rupees)        0
Price (in rupees)        0
location                 0
Carpet Area          80673
Status                   0
Floor                    0
Transaction              0
Furnishing               0
Bathroom                 0
Balcony                  0
Ownership                0
dtype: int64

In [67]:
s.fillna({"Description":"Unknown"},inplace = True)

In [68]:
s.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Status,Floor,Transaction,Furnishing,Bathroom,Balcony,Ownership
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,Ready to Move,10 out of 11,Resale,Unfurnished,1.0,2,Unknown
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,Ready to Move,3 out of 22,Resale,Semi-Furnished,2.0,0,Freehold
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,Ready to Move,10 out of 29,Resale,Unfurnished,2.0,0,Freehold
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,Ready to Move,1 out of 3,Resale,Unfurnished,1.0,1,Unknown
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,Ready to Move,20 out of 42,Resale,Unfurnished,2.0,0,Co-operative Society

In [69]:
s.isnull().sum()

Index                0
Title                0
Description          0
Amount(in rupees)    0
Price (in rupees)    0
location             0
Status               0
Floor                0
Transaction          0
Furnishing           0
Bathroom             0
Balcony              0
Ownership            0
dtype: int64

In [70]:
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        187531 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  187531 non-null  float64
 5   location           187531 non-null  object
 6   Status             187531 non-null  object
 7   Floor              187531 non-null  object
 8   Transaction        187531 non-null  object
 9   Furnishing         187531 non-null  object
 10  Bathroom           187531 non-null  float64
 11  Balcony            187531 non-null  object
 12  Ownership          187531 non-null  object
dtypes: float64(2), int64(1), object(10)
memory usage: 18.6+ MB