Day - 1 
Learning the Pandas and cleaning the data

In [3]:
import pandas as pd

In [10]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("juhibhojani/house-price")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Lenovo\.cache\kagglehub\datasets\juhibhojani\house-price\versions\1

In [5]:
s = pd.read_csv('C:\\Users\\Lenovo\\learning_ml\\Phase_1\\house_prices.csv')

In [6]:
s.describe()

               Index  Price (in rupees)  Dimensions  Plot Area
count  187531.000000       1.698660e+05         0.0        0.0
mean    93765.000000       7.583772e+03         NaN        NaN
std     54135.681003       2.724171e+04         NaN        NaN
min         0.000000       0.000000e+00         NaN        NaN
25%     46882.500000       4.297000e+03         NaN        NaN
50%     93765.000000       6.034000e+03         NaN        NaN
75%    140647.500000       9.450000e+03         NaN        NaN
max    187530.000000       6.700000e+06         NaN        NaN

In [7]:
s.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [8]:
s.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [9]:
s.drop(columns = ['facing','Carpet Area','Car Parking','Super Area','Society','overlooking','Dimensions','Plot Area'], inplace = True)

In [14]:
s.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Status,Floor,Transaction,Furnishing,Bathroom,Balcony,Ownership
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,Ready to Move,10 out of 11,Resale,Unfurnished,1.0,2,Unknown
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,Ready to Move,3 out of 22,Resale,Semi-Furnished,2.0,0,Freehold
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,Ready to Move,10 out of 29,Resale,Unfurnished,2.0,0,Freehold
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,Ready to Move,1 out of 3,Resale,Unfurnished,1.0,1,Unknown
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,Ready to Move,20 out of 42,Resale,Unfurnished,2.0,0,Co-operative Society

In [11]:
s.fillna({"Furnishing":s["Furnishing"].mode()[0]}, inplace = True)
s.fillna({"Balcony": 0}, inplace=True)
s["Bathroom"] = pd.to_numeric(s["Bathroom"], errors="coerce")
s["Bathroom"] = s["Bathroom"].fillna(s["Bathroom"].median())
s.fillna({"Status":"Unknown"}, inplace = True)
s.fillna({"Ownership":"Unknown"}, inplace = True)
s.fillna({"Transaction":s["Transaction"].mode()[0]}, inplace = True)
s.fillna({"Price (in rupees)":s["Price (in rupees)"].mean()}, inplace = True)
s.fillna({"Floor":"Unknown"}, inplace = True)
s.fillna({"Description":"Unknown"},inplace = True)

In [15]:
s.isnull().sum()

Index                0
Title                0
Description          0
Amount(in rupees)    0
Price (in rupees)    0
location             0
Status               0
Floor                0
Transaction          0
Furnishing           0
Bathroom             0
Balcony              0
Ownership            0
dtype: int64

In [70]:
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        187531 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  187531 non-null  float64
 5   location           187531 non-null  object
 6   Status             187531 non-null  object
 7   Floor              187531 non-null  object
 8   Transaction        187531 non-null  object
 9   Furnishing         187531 non-null  object
 10  Bathroom           187531 non-null  float64
 11  Balcony            187531 non-null  object
 12  Ownership          187531 non-null  object
dtypes: float64(2), int64(1), object(10)
memory usage: 18.6+ MB

Day - 2 
Changing the datatypes and training the decision tree uisng sklearn

In [17]:
s = s.drop(columns=['Index'])

s['Title'] = s['Title'].astype('string')
s['Description'] = s['Description'].astype('string')

s['Amount(in rupees)'] = s['Amount(in rupees)'].str.replace(',', '', regex=False)
s['Amount(in rupees)'] = pd.to_numeric(s['Amount(in rupees)'], errors='coerce')

s['Price (in rupees)'] = s['Price (in rupees)'].astype('float32')
s['Bathroom'] = s['Bathroom'].astype('int8')

s['location'] = s['location'].astype('category')
s['Status'] = s['Status'].astype('category')
s['Transaction'] = s['Transaction'].astype('category')
s['Furnishing'] = s['Furnishing'].astype('category')
s['Ownership'] = s['Ownership'].astype('category')

s['Floor'] = s['Floor'].astype('category')

s['Balcony'] = pd.to_numeric(s['Balcony'], errors='coerce').fillna(0).astype('int8')

s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Title              187531 non-null  string
 1   Description        187531 non-null  string
 2   Amount(in rupees)  0 non-null       float64
 3   Price (in rupees)  187531 non-null  float32
 4   location           187531 non-null  category
 5   Status             187531 non-null  category
 6   Floor              187531 non-null  category
 7   Transaction        187531 non-null  category
 8   Furnishing         187531 non-null  category
 9   Bathroom           187531 non-null  int8
 10  Balcony            187531 non-null  int8
 11  Ownership          187531 non-null  category
dtypes: category(6), float32(1), float64(1), int8(2), string(2)
memory usage: 6.7 MB

Dropping two more columns cause they do not affect the decision much

In [18]:
s = s.drop(columns=['Title', 'Description'])

In [19]:
s = pd.get_dummies(s, drop_first=True)

In [22]:
y = s['Price (in rupees)']
X = s.drop(columns = ['Price (in rupees)'])

In [33]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

model = DecisionTreeRegressor(
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=1
)

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=10, min_samples_leaf=5, min_samples_split=10,
                      random_state=1)

In [34]:
y_pred = model.predict(X_test)

In [35]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R2 Score: -0.2610018315650613
MAE: 2074.3681383248163
MSE: 574253122.2137115
RMSE: 23963.579077711063